force-app/main/default/objects/Ham_Directory_Tabset__mdt/Ham_Directory_Tabset__mdt.object-meta.xml
<CustomObject>
    <description>Controls the tab order and visibility on directory page</description>
    <label>Ham Directory Tabset</label>
    <pluralLabel>Ham Directory Tabset</pluralLabel>
</CustomObject>

force-app/main/default/objects/Ham_Directory_Tabset__mdt/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>If checked, the tab is shown</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Ham_Directory_Tabset__mdt/fields/Tab_Order__c.field-meta.xml
<CustomField>
    <fullName>Tab_Order__c</fullName>
    <description>Order in which the tabs are displayed</description>
    <label>Tab Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Ham_DirectoryController.cls
/**
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 * Class Name      : Ham_DirectoryController
 * Author          : <YourName>
 * Created Date    : Jan 5, 2026
 * Last Modified By: <YourName>
 * Last Modified On: Jan 5, 2026
 * Description     : This class implements for......
 *  
 * Change History  :
 *  Date          │   Author     │   Change
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 *  Jan 5, 2026  │ <YourName>   │ Initial version
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 */

 /*----DO NOT USE THIS CLASS----*/

public class Ham_DirectoryController {

	@AuraEnabled(cacheable=true)
	public static List <Ham_Directory_Tabset__mdt> getDirectoryTabset () {
		return [SELECT Id,Label,Is_Active__c,Tab_Order__c FROM Ham_Directory_Tabset__mdt WHERE Is_Active__c = true ORDER BY Tab_Order__c ];
	}

}