force-app/main/default/objects/HAM_Trivia__c/HAM_Trivia__c.object-meta.xml
<CustomObject>
    <label>Trivia</label>
    <nameField>
        <displayFormat>Trivia-{0}</displayFormat>
        <label>Trivia</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trivia</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HAM_Trivia__c/fields/Show_On_Portal__c.field-meta.xml
<CustomField>
    <fullName>Show_On_Portal__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Identifier for a question/set of questions to be shown on portal. DO NOT UNCHECK</description>
    <inlineHelpText>Identifier for a question/set of questions to be shown on portal. DO NOT UNCHECK</inlineHelpText>
    <label>Show On Portal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/HAM_TriviaTriggerHandler.cls
public class HAM_TriviaTriggerHandler {

    public static void afterInsert(List<HAM_Trivia__c> newRecords,List<HAM_Trivia__c> oldRecords) {
        set<Id> newIds = new set<Id>();
        for (HAM_Trivia__c trivia : newRecords) {
             newIds.add(trivia.Id);
        }
        
        List<HAM_Trivia__c> triviaList = [SELECT Id,Show_On_Portal__c,CreatedDate FROM HAM_Trivia__c WHERE Id NOT IN :newIds AND CreatedDate < TODAY AND Show_On_Portal__c = True ];
        //System.debug('triviaList : ' + triviaList);
        
        for(HAM_Trivia__c vartrivia : triviaList){
            vartrivia.Show_On_Portal__c = false;
        }
        
        update triviaList;
    }
}