force-app/main/default/objects/Account/fields/ucinn_ascendv2__Business_Email__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Business_Email__c</fullName>
    <label>Business Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ucinn_ascendv2__Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Contact_Type__c</fullName>
    <label>Constituent Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Trustee</fullName>
            </value>
            <value>
                <fullName>Hamilton Alumni</fullName>
            </value>
            <value>
                <fullName>Hamilton Withdrawn</fullName>
            </value>
            <value>
                <fullName>Kirkland Alumnae</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>Student on Leave</fullName>
            </value>
            <value>
                <fullName>Current Parent</fullName>
            </value>
            <value>
                <fullName>Parent on Leave</fullName>
            </value>
            <value>
                <fullName>Retiree</fullName>
            </value>
            <value>
                <fullName>Past Parent</fullName>
            </value>
            <value>
                <fullName>Grandparent</fullName>
            </value>
            <value>
                <fullName>Former Employee</fullName>
            </value>
            <value>
                <fullName>Spouse of Alumni or Trustee</fullName>
            </value>
            <value>
                <fullName>Surviving Spouse</fullName>
            </value>
            <value>
                <fullName>Parent of Withdrawn</fullName>
            </value>
            <value>
                <fullName>Estate</fullName>
            </value>
            <value>
                <fullName>Organization Contact</fullName>
            </value>
            <value>
                <fullName>Incoming Student</fullName>
            </value>
            <value>
                <fullName>Incoming Parent</fullName>
            </value>
            <value>
                <fullName>Friend</fullName>
                <default>true</default>
                <label>Friend</label>
            </value>
            <value>
                <fullName>Graduating Student</fullName>
            </value>
            <value>
                <fullName>Graduating Parent</fullName>
            </value>
            <value>
                <fullName>Tribute Donor</fullName>
            </value>
            <value>
                <fullName>Former Incoming Student</fullName>
            </value>
            <value>
                <fullName>Former Incoming Parent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/ucinn_ascendv2__Donor_ID__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Donor_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Donor ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/ucinn_ascendv2__External_System_ID__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__External_System_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Generally used for data migration of referential records from an external system.</description>
    <externalId>true</externalId>
    <label>External System ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/ucinn_ascendv2__Personal_Email__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Personal_Email__c</fullName>
    <label>Personal Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/GL_Feeder__c/GL_Feeder__c.object-meta.xml
<CustomObject>
    <label>GL Feeder</label>
    <nameField>
        <displayFormat>GL-{00000000}</displayFormat>
        <label>GL Feeder Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GL Feeder</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/HAM_Fiscal_Year__c.field-meta.xml
<CustomField>
    <fullName>HAM_Fiscal_Year__c</fullName>
    <description>Returns fiscal year based on credit date</description>
    <formula>&quot;FY-&quot; + TEXT(YEAR( ucinn_ascendv2__Credit_Date__c ) + IF(MONTH( ucinn_ascendv2__Credit_Date__c ) &gt;= 7, 1, 0))</formula>
    <label>Fiscal Year</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ucinn_ascendv2__Adjusted_Gift__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Adjusted_Gift__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Adjusted Pledge/Gift</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Adjustments</relationshipLabel>
    <relationshipName>Opportunities_Adjusted_Gift</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ucinn_ascendv2__Contact__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Constituent</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Pledges / Gifts</relationshipLabel>
    <relationshipName>Opportunities_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ucinn_ascendv2__Credit_Date__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Credit_Date__c</fullName>
    <description>Previously Start_Date__c.</description>
    <label>Credit Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ucinn_ascendv2__Designation__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Designation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Designation</label>
    <referenceTo>ucinn_ascendv2__Designation__c</referenceTo>
    <relationshipLabel>Pledges</relationshipLabel>
    <relationshipName>Opportunities_Designation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ucinn_ascendv2__External_System_ID__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__External_System_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Generally used for data migration of referential records from an external system.</description>
    <externalId>true</externalId>
    <label>External System ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ucinn_ascendv2__Payment_Group_ID__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Payment_Group_ID__c</fullName>
    <label>Payment Group ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ucinn_ascendv2__Send_to_G_L__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Send_to_G_L__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send to G / L</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ucinn_ascendv2__Session__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>ucinn_ascendv2__Session__c</referenceTo>
    <relationshipLabel>Pledges / Gifts (Session)</relationshipLabel>
    <relationshipName>Opportunities_Session</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ucinn_ascendv2__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Start_Date__c</fullName>
    <description>Start date for Recurring Gifts</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ucinn_ascendv2__Tender_Type_for_Gifts__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Tender_Type_for_Gifts__c</fullName>
    <label>Tender Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ham_BATCH_GLFeederTest.cls
@isTest
public with sharing class ham_BATCH_GLFeederTest {

    @TestSetup
    public static void setupData(){
        ucinn_ascendv2.ascend_UTIL_TDTMTrigger.toggleTDTMTrigger(new Account().getSObjectType().getDescribe().getName(), false);
        ucinn_ascendv2.ascend_UTIL_TDTMTrigger.toggleTDTMTrigger(new Contact().getSObjectType().getDescribe().getName(), false);
        ucinn_ascendv2.ascend_UTIL_TDTMTrigger.toggleTDTMTrigger(new Campaign().getSObjectType().getDescribe().getName(), false);
        ucinn_ascendv2.ascend_UTIL_TDTMTrigger.toggleTDTMTrigger(new ucinn_ascendv2__Designation__c().getSObjectType().getDescribe().getName(), false);

        List<Account> testAccounts = new List<Account> { 
            new Account(
                Name = 'Household Acc', 
                ucinn_ascendv2__Donor_Id__c = '1000002',
                ucinn_ascendv2__Business_Email__c = 'hhAcc@gmail.com'
            )
        };
        insert testAccounts;
        
        List<ucinn_ascendv2__Designation__c> newDesignations = new List<ucinn_ascendv2__Designation__c> {
            new ucinn_ascendv2__Designation__c(
                Name = '0000',
                ucinn_ascendv2__Designation_Name__c = 'Test Designation 00',
                ucinn_ascendv2__External_System_Id__c = '0000',
                ucinn_ascendv2__G_L_Effective_Date__c = System.today().addDays(-1)
            )
        };
        insert newDesignations;

        Id devRecordTypeId = Schema.SObjectType.Campaign.getRecordTypeInfosByName().get('Appeal').getRecordTypeId();
        List<Campaign> newCampaigns = new List<Campaign> {
            new Campaign(
                Name = 'Test Appeal 00',
                RecordTypeId = devRecordTypeId,
                HAM_Fiscal_Year__c = '2020'
            )
        };
        insert newCampaigns;

        List<Contact> contactsList =  new List<Contact> {
            new Contact(
                FirstName = 'Test Constituent',
                LastName = 'Test_000',
                ucinn_ascendv2__Contact_Type__c = 'Friend',
                ucinn_ascendv2__Donor_Id__c = '01000200001',
                ucinn_ascendv2__Personal_Email__c = 'myEmail@personal.com',
                AccountId = testAccounts[0].Id
            )
        };

        insert contactsList;
    }

    @IsTest 
    public static void outrightGiftTest() {
        
        ucinn_ascendv2.ascend_UTIL_TDTMTrigger.toggleTDTMTrigger(new ucinn_ascendv2__Session__c().getSObjectType().getDescribe().getName(), false);
        ucinn_ascendv2.ascend_UTIL_TDTMTrigger.toggleTDTMTrigger(new ucinn_ascendv2__Designation_Detail__c().getSObjectType().getDescribe().getName(), false);
        ucinn_ascendv2.ascend_UTIL_TDTMTrigger.toggleTDTMTrigger(new ucinn_ascendv2__Payment__c().getSObjectType().getDescribe().getName(), false);
        ucinn_ascendv2.ascend_UTIL_TDTMTrigger.toggleTDTMTrigger(new Opportunity().getSObjectType().getDescribe().getName(), false);
                
        Contact myContact = [SELECT Id, FirstName, LastName FROM Contact ORDER BY LastName ASC LIMIT 1];
        Account myAccount = [SELECT Id, Name FROM Account LIMIT 1];
        ucinn_ascendv2__Designation__c testDesignation = [SELECT Id FROM ucinn_ascendv2__Designation__c LIMIT 1];
        Campaign testCampaign = [SELECT Id FROM Campaign LIMIT 1];
        
        ucinn_ascendv2__Session__c newSession = new ucinn_ascendv2__Session__c(
            ucinn_ascendv2__Session_Date__c = System.Today(),
            Name = 'OutrightGiftTest',
            ucinn_ascendv2__Is_Ready_for_G_L__c = true,
            ucinn_ascendv2__Session_Totals_Approved__c = System.now(),
            ucinn_ascendv2__Is_Sent_to_G_L__c = false,
            HAM_Is_Sent_to_GL_Feeder__c = false
        );
        insert newSession;

        Opportunity outrightGift = new Opportunity(
            Name = 'New Outright Gift',
            StageName = 'Paid',
            CloseDate = System.Today(),
            ucinn_ascendv2__Credit_Date__c = System.Today(),
            RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Gift').getRecordTypeId(),
            ucinn_ascendv2__Contact__c = myContact.Id,
            Amount = 2000.00,
            ucinn_ascendv2__Start_Date__c = System.Today(),
            ucinn_ascendv2__Session__c = newSession.Id,
            ucinn_ascendv2__Designation__c = testDesignation.Id,
            CampaignId = testCampaign.id,
            Type = 'Outright Gift'
        );
        insert outrightGift;

        ucinn_ascendv2__Designation_Detail__c newDesDetail = new ucinn_ascendv2__Designation_Detail__c(
            ucinn_ascendv2__Contact__c = myContact.Id,
            ucinn_ascendv2__Opportunity__c = outrightGift.Id,
            ucinn_ascendv2__Session__c = newSession.Id, 
            ucinn_ascendv2__Designation__c = testDesignation.Id,
            ucinn_ascendv2__Amount__c = 2000,
            ucinn_ascendv2__Campaign__c = testCampaign.Id
        );
        insert newDesDetail;

        List<ucinn_ascendv2__Payment__c> newPaymentsList = new List<ucinn_ascendv2__Payment__c> {
            new ucinn_ascendv2__Payment__c(
                ucinn_ascendv2__Contact__c = myContact.Id,
                ucinn_ascendv2__Payment_Amount__c = 1000,
                ucinn_ascendv2__Credit_Date__c = System.Today(),
                ucinn_ascendv2__Session__c = newSession.Id,
                ucinn_ascendv2__Opportunity__c = outrightGift.Id,
                ucinn_ascendv2__Designation__c = testDesignation.Id,
                ucinn_ascendv2__Designation_Detail__c = newDesDetail.Id,
                ucinn_ascendv2__Transaction_Type__c = 'Outright Gift',
                ucinn_ascendv2__Tender_Type_for_Gifts__c = 'Cash',
                ucinn_ascendv2__Payment_Group_Id__c = '00001',
                ucinn_ascendv2__Send_to_G_L__c = true
            ),
            new ucinn_ascendv2__Payment__c(
                ucinn_ascendv2__Contact__c = myContact.Id,
                ucinn_ascendv2__Payment_Amount__c = 1000,
                ucinn_ascendv2__Credit_Date__c = System.Today(),
                ucinn_ascendv2__Session__c = newSession.Id,
                ucinn_ascendv2__Opportunity__c = outrightGift.Id,
                ucinn_ascendv2__Designation__c = testDesignation.Id,
                ucinn_ascendv2__Designation_Detail__c = newDesDetail.Id,
                ucinn_ascendv2__Transaction_Type__c = 'Outright Gift',
                ucinn_ascendv2__Tender_Type_for_Gifts__c = 'Cash',
                ucinn_ascendv2__Payment_Group_Id__c = '00001',
                ucinn_ascendv2__Send_to_G_L__c = true
            ),
            new ucinn_ascendv2__Payment__c(
                ucinn_ascendv2__Account__c = myAccount.Id,
                ucinn_ascendv2__Payment_Amount__c = 1000,
                ucinn_ascendv2__Credit_Date__c = System.Today(),
                ucinn_ascendv2__Session__c = newSession.Id,
                ucinn_ascendv2__Opportunity__c = outrightGift.Id,
                ucinn_ascendv2__Designation__c = testDesignation.Id,
                ucinn_ascendv2__Designation_Detail__c = newDesDetail.Id,
                ucinn_ascendv2__Transaction_Type__c = 'Outright Gift',
                ucinn_ascendv2__Tender_Type_for_Gifts__c = 'Cash',
                ucinn_ascendv2__Payment_Group_Id__c = '00001',
                ucinn_ascendv2__Send_to_G_L__c = true
            )
        };
            
        insert newPaymentsList;
      
        Test.startTest();
        ham_BATCH_GLFeeder bankFeed = new ham_BATCH_GLFeeder();
        Database.executeBatch(bankFeed);
        Test.stopTest();

        List<GL_Feeder__c> feeders = [SELECT id FROM GL_Feeder__c];
        System.assertEquals(3, feeders.size());
    }
    
    

    @IsTest 
    public static void adjustmentTest() {
        
        ucinn_ascendv2.ascend_UTIL_TDTMTrigger.toggleTDTMTrigger(new ucinn_ascendv2__Session__c().getSObjectType().getDescribe().getName(), false);
        ucinn_ascendv2.ascend_UTIL_TDTMTrigger.toggleTDTMTrigger(new ucinn_ascendv2__Designation_Detail__c().getSObjectType().getDescribe().getName(), false);
        ucinn_ascendv2.ascend_UTIL_TDTMTrigger.toggleTDTMTrigger(new ucinn_ascendv2__Payment__c().getSObjectType().getDescribe().getName(), false);
        ucinn_ascendv2.ascend_UTIL_TDTMTrigger.toggleTDTMTrigger(new Opportunity().getSObjectType().getDescribe().getName(), false);
                
        Contact myContact = [SELECT Id, FirstName, LastName FROM Contact ORDER BY LastName ASC LIMIT 1];
        Account myAccount = [SELECT Id, Name FROM Account LIMIT 1];
        ucinn_ascendv2__Designation__c testDesignation = [SELECT Id FROM ucinn_ascendv2__Designation__c LIMIT 1];
        Campaign testCampaign = [SELECT Id FROM Campaign LIMIT 1];
        
        ucinn_ascendv2__Session__c oldSession = new ucinn_ascendv2__Session__c(
            ucinn_ascendv2__Session_Date__c = System.Today(),
            Name = 'oldSession',
            ucinn_ascendv2__Is_Ready_for_G_L__c = false,
            ucinn_ascendv2__Session_Totals_Approved__c = System.now(),
            ucinn_ascendv2__Is_Sent_to_G_L__c = true,
            HAM_Is_Sent_to_GL_Feeder__c = true
        );
        insert oldSession;
        
        ucinn_ascendv2__Session__c newSession = new ucinn_ascendv2__Session__c(
            ucinn_ascendv2__Session_Date__c = System.Today(),
            Name = 'OutrightGiftTest',
            ucinn_ascendv2__Is_Ready_for_G_L__c = true,
            ucinn_ascendv2__Session_Totals_Approved__c = System.now(),
            ucinn_ascendv2__Is_Sent_to_G_L__c = false,
            HAM_Is_Sent_to_GL_Feeder__c = false
        );
        insert newSession;

        Opportunity adjustedGift = new Opportunity(
            Name = 'Adjusted Gift',
            StageName = 'Paid',
            CloseDate = System.Today(),
            ucinn_ascendv2__Credit_Date__c = System.Today(),
            RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Gift').getRecordTypeId(),
            ucinn_ascendv2__Contact__c = myContact.Id,
            Amount = 2000.00,
            ucinn_ascendv2__Start_Date__c = System.Today(),
            ucinn_ascendv2__Session__c = newSession.Id,
            ucinn_ascendv2__Designation__c = testDesignation.Id,
            CampaignId = testCampaign.id,
            Type = 'Outright Gift'
        );
        insert adjustedGift;

        Opportunity outrightGift = new Opportunity(
            Name = 'New Outright Gift',
            StageName = 'Paid',
            CloseDate = System.Today(),
            ucinn_ascendv2__Credit_Date__c = System.Today(),
            RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Gift').getRecordTypeId(),
            ucinn_ascendv2__Contact__c = myContact.Id,
            Amount = 2000.00,
            ucinn_ascendv2__Start_Date__c = System.Today(),
            ucinn_ascendv2__Session__c = newSession.Id,
            ucinn_ascendv2__Designation__c = testDesignation.Id,
            CampaignId = testCampaign.id,
            Type = 'Outright Gift'
        );
        insert outrightGift;

        ucinn_ascendv2__Designation_Detail__c newDesDetail = new ucinn_ascendv2__Designation_Detail__c(
            ucinn_ascendv2__Contact__c = myContact.Id,
            ucinn_ascendv2__Opportunity__c = outrightGift.Id,
            ucinn_ascendv2__Session__c = newSession.Id, 
            ucinn_ascendv2__Designation__c = testDesignation.Id,
            ucinn_ascendv2__Amount__c = 2000,
            ucinn_ascendv2__Campaign__c = testCampaign.Id
        );
        insert newDesDetail;

        List<ucinn_ascendv2__Payment__c> newPaymentsList = new List<ucinn_ascendv2__Payment__c> {
            new ucinn_ascendv2__Payment__c(
                ucinn_ascendv2__Contact__c = myContact.Id,
                ucinn_ascendv2__Payment_Amount__c = 1000,
                ucinn_ascendv2__Credit_Date__c = System.Today(),
                ucinn_ascendv2__Session__c = oldSession.Id,
                ucinn_ascendv2__Opportunity__c = adjustedGift.Id,
                ucinn_ascendv2__Designation__c = testDesignation.Id,
                ucinn_ascendv2__Designation_Detail__c = newDesDetail.Id,
                ucinn_ascendv2__Transaction_Type__c = 'Outright Gift',
                ucinn_ascendv2__Tender_Type_for_Gifts__c = 'Cash',
                ucinn_ascendv2__Payment_Group_Id__c = '00001',
                ucinn_ascendv2__Send_to_G_L__c = true
            ),
            new ucinn_ascendv2__Payment__c(
                ucinn_ascendv2__Contact__c = myContact.Id,
                ucinn_ascendv2__Payment_Amount__c = 1000,
                ucinn_ascendv2__Credit_Date__c = System.Today(),
                ucinn_ascendv2__Session__c = oldSession.Id,
                ucinn_ascendv2__Opportunity__c = adjustedGift.Id,
                ucinn_ascendv2__Designation__c = testDesignation.Id,
                ucinn_ascendv2__Designation_Detail__c = newDesDetail.Id,
                ucinn_ascendv2__Transaction_Type__c = 'Outright Gift',
                ucinn_ascendv2__Tender_Type_for_Gifts__c = 'Cash',
                ucinn_ascendv2__Payment_Group_Id__c = '00001',
                ucinn_ascendv2__Send_to_G_L__c = true
            ),
            new ucinn_ascendv2__Payment__c(
                ucinn_ascendv2__Account__c = myAccount.Id,
                ucinn_ascendv2__Payment_Amount__c = 1000,
                ucinn_ascendv2__Credit_Date__c = System.Today(),
                ucinn_ascendv2__Session__c = oldSession.Id,
                ucinn_ascendv2__Opportunity__c = adjustedGift.Id,
                ucinn_ascendv2__Designation__c = testDesignation.Id,
                ucinn_ascendv2__Designation_Detail__c = newDesDetail.Id,
                ucinn_ascendv2__Transaction_Type__c = 'Outright Gift',
                ucinn_ascendv2__Tender_Type_for_Gifts__c = 'Cash',
                ucinn_ascendv2__Payment_Group_Id__c = '00001',
                ucinn_ascendv2__Send_to_G_L__c = true
            ),
                
            new ucinn_ascendv2__Payment__c(
                ucinn_ascendv2__Contact__c = myContact.Id,
                ucinn_ascendv2__Payment_Amount__c = 1000,
                ucinn_ascendv2__Credit_Date__c = System.Today(),
                ucinn_ascendv2__Session__c = newSession.Id,
                ucinn_ascendv2__Adjusted_Gift__c = adjustedGift.id,
                ucinn_ascendv2__Opportunity__c = outrightGift.Id,
                ucinn_ascendv2__Designation__c = testDesignation.Id,
                ucinn_ascendv2__Designation_Detail__c = newDesDetail.Id,
                ucinn_ascendv2__Transaction_Type__c = 'Outright Gift',
                ucinn_ascendv2__Tender_Type_for_Gifts__c = 'Cash',
                ucinn_ascendv2__Payment_Group_Id__c = '00001',
                ucinn_ascendv2__Send_to_G_L__c = true
            ),
            new ucinn_ascendv2__Payment__c(
                ucinn_ascendv2__Contact__c = myContact.Id,
                ucinn_ascendv2__Payment_Amount__c = 1000,
                ucinn_ascendv2__Credit_Date__c = System.Today(),
                ucinn_ascendv2__Session__c = newSession.Id,
                ucinn_ascendv2__Adjusted_Gift__c = adjustedGift.id,
                ucinn_ascendv2__Opportunity__c = outrightGift.Id,
                ucinn_ascendv2__Designation__c = testDesignation.Id,
                ucinn_ascendv2__Designation_Detail__c = newDesDetail.Id,
                ucinn_ascendv2__Transaction_Type__c = 'Outright Gift',
                ucinn_ascendv2__Tender_Type_for_Gifts__c = 'Cash',
                ucinn_ascendv2__Payment_Group_Id__c = '00001',
                ucinn_ascendv2__Send_to_G_L__c = true
            ),
            new ucinn_ascendv2__Payment__c(
                ucinn_ascendv2__Account__c = myAccount.Id,
                ucinn_ascendv2__Payment_Amount__c = 1000,
                ucinn_ascendv2__Credit_Date__c = System.Today(),
                ucinn_ascendv2__Session__c = newSession.Id,
                ucinn_ascendv2__Adjusted_Gift__c = adjustedGift.id,
                ucinn_ascendv2__Opportunity__c = outrightGift.Id,
                ucinn_ascendv2__Designation__c = testDesignation.Id,
                ucinn_ascendv2__Designation_Detail__c = newDesDetail.Id,
                ucinn_ascendv2__Transaction_Type__c = 'Outright Gift',
                ucinn_ascendv2__Tender_Type_for_Gifts__c = 'Cash',
                ucinn_ascendv2__Payment_Group_Id__c = '00001',
                ucinn_ascendv2__Send_to_G_L__c = true
            )
        };
            
        insert newPaymentsList;
      
        Test.startTest();
        ham_BATCH_GLFeeder bankFeed = new ham_BATCH_GLFeeder();
        Database.executeBatch(bankFeed);
        String cronExp = '0 0 0 * * ?'; 
        System.schedule('Test Batch', cronExp, new ham_SCHED_GLFeeder());
        Test.stopTest();

        List<GL_Feeder__c> feeders = [SELECT id FROM GL_Feeder__c];
        System.assertEquals(6, feeders.size());
    }
}