force-app/main/default/objects/Opportunity/fields/ucinn_ascendv2__Amount_Paid_to_Date_Roll_Up__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Amount_Paid_to_Date_Roll_Up__c</fullName>
    <label>Amount Paid to Date</label>
    <summarizedField>ucinn_ascendv2__Designation_Detail__c.ucinn_ascendv2__Amount_Paid_to_Date_Roll_Up__c</summarizedField>
    <summaryForeignKey>ucinn_ascendv2__Designation_Detail__c.ucinn_ascendv2__Opportunity__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ucinn_ascendv2__Contact__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Constituent</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Pledges / Gifts</relationshipLabel>
    <relationshipName>Opportunities_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ucinn_ascendv2__Designation__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Designation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Designation</label>
    <referenceTo>ucinn_ascendv2__Designation__c</referenceTo>
    <relationshipLabel>Pledges</relationshipLabel>
    <relationshipName>Opportunities_Designation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ucinn_ascendv2__Remaining_Amount_Due_Formula__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Remaining_Amount_Due_Formula__c</fullName>
    <description>CC 10/5 Uses Amount Paid to Date Roll up instead of Designation_Detail_Amount_Paid_to_Date__c to exclude designation mistmatch. Update: This includes all payments made for the opportunity to determine remaining amount due. Record Type Change, Pledge_Amount__c = Funded_Amount__c = Amount. previous logic = IF(Amount - Amount_Paid_to_Date__c &gt; 0,
Amount - Amount_Paid_to_Date__c, 0)</description>
    <formula>IF((RecordType.DeveloperName == &apos;Recurring_Gift&apos;),
    0.00,
    IF(ISPICKVAL(StageName, &quot;Written Off&quot;) || ISPICKVAL(StageName, &quot;Cancelled&quot;) || ISPICKVAL(StageName, &quot;Void&quot;),
        0.00,
        IF(Amount - ucinn_ascendv2__Amount_Paid_to_Date_Roll_Up__c &gt; 0,
            IF(ucinn_ascendv2__Pledge_Underpayment_Total__c &lt;= 0,
                Amount - ucinn_ascendv2__Amount_Paid_to_Date_Roll_Up__c,
                Amount - ucinn_ascendv2__Amount_Paid_to_Date_Roll_Up__c - ucinn_ascendv2__Pledge_Underpayment_Total__c),
        0.00)
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remaining Amount Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/PledgeHelper.cls
public without sharing class PledgeHelper {
    public static List<HamGivingController.PledgeWrapper> getPledges(String contactId){
        List<HamGivingController.PledgeWrapper> pledgeList = new List<HamGivingController.PledgeWrapper>();
        List<Opportunity> pledges = [
            SELECT Id, ucinn_ascendv2__Remaining_Amount_Due_Formula__c, 
                ucinn_ascendv2__Amount_Paid_to_Date_Roll_Up__c, 
                Amount, 
                ucinn_ascendv2__Designation__r.ucinn_ascendv2__G_L_Effective_Date__c, 
                ucinn_ascendv2__Designation__r.ucinn_ascendv2__Designation_Name__c
            FROM Opportunity
            WHERE StageName != 'Written Off'
            AND StageName != 'Paid'
            AND RecordType.DeveloperName = 'Pledge'
            AND Type != 'Payroll'
            AND Type != 'Revocable Bequest Pledge'
            AND Type != 'PGBEQ (Revocable Bequest)'
            AND ucinn_ascendv2__Designation__c != null
            AND ucinn_ascendv2__Contact__c = :contactId
        ];

        for (Opportunity pledge : pledges) {
            pledgeList.add(new HamGivingController.PledgeWrapper(pledge));
        }
        return pledgeList;
    }
}