force-app/main/default/objects/Contact/fields/HAM_Trivia_Attempted__c.field-meta.xml
<CustomField>
    <fullName>HAM_Trivia_Attempted__c</fullName>
    <description>To auto-reset the HAM Trivia Attempted checkbox. If the HAM Trivia Attempted Date NOT EQUALS Null, AND HAM Trivia Attempted Date EQUALS Today&apos;s date, Then we check it, else we uncheck it.</description>
    <formula>IF(
 AND(
    NOT(ISBLANK(HAM_Trivia_Attempted_Date__c)),
    HAM_Trivia_Attempted_Date__c = TODAY()
),
True,
False
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>To auto-reset the HAM Trivia Attempted checkbox.</inlineHelpText>
    <label>HAM Trivia Attempted?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/HAM_Trivia_Score__c.field-meta.xml
<CustomField>
    <fullName>HAM_Trivia_Score__c</fullName>
    <description>Stores the score of Hamilton Trivia on Alumni Portal</description>
    <inlineHelpText>Stores the score of Hamilton Trivia on Alumni Portal</inlineHelpText>
    <label>HAM Trivia Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HAM_Trivia__c/HAM_Trivia__c.object-meta.xml
<CustomObject>
    <label>Trivia</label>
    <nameField>
        <displayFormat>Trivia-{0}</displayFormat>
        <label>Trivia</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trivia</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HAM_Trivia__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Identifier for an active question. Only one question is active per day.</description>
    <inlineHelpText>Identifier for an active question. Only one question is active per day.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HAM_Trivia__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <displayFormat>{0}</displayFormat>
    <inlineHelpText>Order is helpful to identify the questions in reoccurring cycles</inlineHelpText>
    <label>Order</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/HAM_Trivia__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <inlineHelpText>The Points/Weightage of the question</inlineHelpText>
    <label>Points</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HAM_Trivia__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <inlineHelpText>A question can have a max of 50K characters</inlineHelpText>
    <label>Question</label>
    <length>50000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/HAM_Trivia__c/fields/Show_On_Portal__c.field-meta.xml
<CustomField>
    <fullName>Show_On_Portal__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Identifier for a question/set of questions to be shown on portal. DO NOT UNCHECK</description>
    <inlineHelpText>Identifier for a question/set of questions to be shown on portal. DO NOT UNCHECK</inlineHelpText>
    <label>Show On Portal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HAM_Trivia_Options__c/HAM_Trivia_Options__c.object-meta.xml
<CustomObject>
    <label>Trivia Options</label>
    <nameField>
        <displayFormat>Option-{0}</displayFormat>
        <label>Trivia Option</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trivia Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HAM_Trivia_Options__c/fields/Display_Order__c.field-meta.xml
<CustomField>
    <fullName>Display_Order__c</fullName>
    <inlineHelpText>For ordering options</inlineHelpText>
    <label>Display Order</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HAM_Trivia_Options__c/fields/Is_Correct__c.field-meta.xml
<CustomField>
    <fullName>Is_Correct__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Correct option is checked</inlineHelpText>
    <label>Is Correct?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HAM_Trivia_Options__c/fields/Option__c.field-meta.xml
<CustomField>
    <fullName>Option__c</fullName>
    <inlineHelpText>Max 255 characters</inlineHelpText>
    <label>Option</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/HAM_Trivia_Options__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <referenceTo>HAM_Trivia__c</referenceTo>
    <relationshipLabel>Trivia Options</relationshipLabel>
    <relationshipName>Trivia_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/HAM_TriviaControllerTest.cls
@SuppressWarnings('PMD.NoTrailingWhitespace, PMD.ApexUnitTestClassShouldHaveRunAs, PMD.ApexUnitTestClassShouldHaveAsserts, PMD.ExcessiveClassLength, PME.ExcessivePublicCount, PMD.ApexCRUDViolation, PMD.EmptyIfStmt, PMD.EmptyStatementBlock, PMD.AvoidNonRestrictiveQueries, PMD.CyclomaticComplexity, PMD.CognitiveComplexity, PMD.NcssCount, PMD.NcssTypeCount, PMD.DetectCopyPasteForApex, PMD.LocalVariableNamingConventions, PMD.ExcessiveParameterList, PMD.ApexSOQLInjection, PMD.AvoidDeeplyNestedIfStmts, PMD.AvoidDebugStatements, PMD.StdCyclomaticComplexity, PMD.NcssMethodCount')
@isTest
public class HAM_TriviaControllerTest {
    
     /* ---------------------------
       Test Data Setup
    ---------------------------- */
    @testSetup
    static void setupData() {

        // Create Contact
            Contact con = new Contact(
            LastName = 'Test User',
            //HAM_Trivia_Attempted__c = false,
            HAM_Trivia_Score__c = 0
        );
        insert con;
        
        // Create Trivia Question
            HAM_Trivia__c trivia = new HAM_Trivia__c(
            Question__c = 'What is Apex?',
            Active__c = true,
            Show_On_Portal__c = true,
            //Order__c = 1,
            Points__c = 10
        );
        insert trivia;
        
          // Create Trivia Options
          // Create Trivia Options
        List<HAM_Trivia_Options__c> options = new List<HAM_Trivia_Options__c>{
            new HAM_Trivia_Options__c(
                Question__c = trivia.Id,
                Option__c = 'Programming Language',
                Is_Correct__c = true,
                Display_Order__c = '1'
            ),
            new HAM_Trivia_Options__c(
                Question__c = trivia.Id,
                Option__c = 'Database',
                Is_Correct__c = false,
                Display_Order__c = '2'
            )
        };
        insert options;     
    } 
    
    /* ---------------------------
       Test getTriviaQuestionAndOptions
    ---------------------------- */
    @IsTest
    static void testGetTriviaQuestionAndOptions() {

        Contact con = [SELECT Id FROM Contact LIMIT 1];

        Test.startTest();
        HAM_TriviaController.TriviaWrapper wrapper =
            HAM_TriviaController.getTriviaQuestionAndOptions(con.Id);
        Test.stopTest();
        
    }
    
    /* ---------------------------
       Test updateTriviaInfoOnConstituent
    ---------------------------- */
    @IsTest
    static void testUpdateTriviaInfoOnConstituent() {

        Contact con = [SELECT Id, HAM_Trivia_Score__c FROM Contact LIMIT 1];

        Test.startTest();
        String result = HAM_TriviaController.updateTriviaInfoOnConstituent(
            con.Id,
            10,
            'Programming Language'
        );
        Test.stopTest();
    }
}