force-app/main/default/objects/Contact/fields/HAM_Trivia_Attempted__c.field-meta.xml
<CustomField>
    <fullName>HAM_Trivia_Attempted__c</fullName>
    <description>To auto-reset the HAM Trivia Attempted checkbox. If the HAM Trivia Attempted Date NOT EQUALS Null, AND HAM Trivia Attempted Date EQUALS Today&apos;s date, Then we check it, else we uncheck it.</description>
    <formula>IF(
 AND(
    NOT(ISBLANK(HAM_Trivia_Attempted_Date__c)),
    HAM_Trivia_Attempted_Date__c = TODAY()
),
True,
False
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>To auto-reset the HAM Trivia Attempted checkbox.</inlineHelpText>
    <label>HAM Trivia Attempted?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/HAM_Trivia_Attempted_Date__c.field-meta.xml
<CustomField>
    <fullName>HAM_Trivia_Attempted_Date__c</fullName>
    <description>Captures the date when an user attempts the Hamilton Trivia in the Alumni Portal</description>
    <inlineHelpText>Captures the date when an user attempts the Hamilton Trivia in the Alumni Portal</inlineHelpText>
    <label>HAM Trivia Attempted Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/HAM_Trivia_Option_Chosen__c.field-meta.xml
<CustomField>
    <fullName>HAM_Trivia_Option_Chosen__c</fullName>
    <description>Stores the option chosen for particular Hamilton Trivia question on Alumni Portal</description>
    <inlineHelpText>Stores the option chosen for particular Hamilton Trivia question on Alumni Portal</inlineHelpText>
    <label>HAM Trivia Option Chosen</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/HAM_Trivia_Score__c.field-meta.xml
<CustomField>
    <fullName>HAM_Trivia_Score__c</fullName>
    <description>Stores the score of Hamilton Trivia on Alumni Portal</description>
    <inlineHelpText>Stores the score of Hamilton Trivia on Alumni Portal</inlineHelpText>
    <label>HAM Trivia Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HAM_Trivia__c/HAM_Trivia__c.object-meta.xml
<CustomObject>
    <label>Trivia</label>
    <nameField>
        <displayFormat>Trivia-{0}</displayFormat>
        <label>Trivia</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trivia</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HAM_Trivia__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Identifier for an active question. Only one question is active per day.</description>
    <inlineHelpText>Identifier for an active question. Only one question is active per day.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HAM_Trivia__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <displayFormat>{0}</displayFormat>
    <inlineHelpText>Order is helpful to identify the questions in reoccurring cycles</inlineHelpText>
    <label>Order</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/HAM_Trivia__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <inlineHelpText>The Points/Weightage of the question</inlineHelpText>
    <label>Points</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HAM_Trivia__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <inlineHelpText>A question can have a max of 50K characters</inlineHelpText>
    <label>Question</label>
    <length>50000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/HAM_Trivia__c/fields/Show_On_Portal__c.field-meta.xml
<CustomField>
    <fullName>Show_On_Portal__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Identifier for a question/set of questions to be shown on portal. DO NOT UNCHECK</description>
    <inlineHelpText>Identifier for a question/set of questions to be shown on portal. DO NOT UNCHECK</inlineHelpText>
    <label>Show On Portal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HAM_Trivia_Options__c/HAM_Trivia_Options__c.object-meta.xml
<CustomObject>
    <label>Trivia Options</label>
    <nameField>
        <displayFormat>Option-{0}</displayFormat>
        <label>Trivia Option</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trivia Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HAM_Trivia_Options__c/fields/Display_Order__c.field-meta.xml
<CustomField>
    <fullName>Display_Order__c</fullName>
    <inlineHelpText>For ordering options</inlineHelpText>
    <label>Display Order</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HAM_Trivia_Options__c/fields/Is_Correct__c.field-meta.xml
<CustomField>
    <fullName>Is_Correct__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Correct option is checked</inlineHelpText>
    <label>Is Correct?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HAM_Trivia_Options__c/fields/Option__c.field-meta.xml
<CustomField>
    <fullName>Option__c</fullName>
    <inlineHelpText>Max 255 characters</inlineHelpText>
    <label>Option</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/HAM_Trivia_Options__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <referenceTo>HAM_Trivia__c</referenceTo>
    <relationshipLabel>Trivia Options</relationshipLabel>
    <relationshipName>Trivia_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/HAM_TriviaController.cls
/**
* @File Name : HAM_TriviaController.cls
* @Description : Serves the trivia data. Updates the constituent's trivia data after submission
* @Author : Immanuel
* @Last Modified By : Immanuel
* @Last Modified On : December 13, 2025
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | December 13, 2025 | Immanuel | Initial Version
**/
@SuppressWarnings('PMD.FormalParameterNamingConventions, PMD.DebugsShouldUseLoggingLevel, PMD.ApexDoc, PMD.FieldNamingConventions, PMD.NoTrailingWhitespace, PMD.ExcessiveClassLength, PME.ExcessivePublicCount, PMD.ApexCRUDViolation, PMD.EmptyIfStmt, PMD.EmptyStatementBlock, PMD.AvoidNonRestrictiveQueries, PMD.CyclomaticComplexity, PMD.CognitiveComplexity, PMD.NcssCount, PMD.NcssTypeCount, PMD.DetectCopyPasteForApex, PMD.LocalVariableNamingConventions, PMD.ExcessiveParameterList, PMD.ApexSOQLInjection, PMD.AvoidDeeplyNestedIfStmts, PMD.AvoidDebugStatements, PMD.StdCyclomaticComplexity, PMD.NcssMethodCount')
public without sharing class HAM_TriviaController {

	public class TriviaWrapper{

		@AuraEnabled public Contact Constituent;
	 	@AuraEnabled public HAM_Trivia__c Trivia;

		public TriviaWrapper(Contact Constituent,HAM_Trivia__c Trivia){
			this.Constituent = Constituent;
			this.Trivia = Trivia;
		}
	}
	
	//Serves the trivia data to the component
	@AuraEnabled(cacheable=true)
	public static TriviaWrapper getTriviaQuestionAndOptions(Id ContactId){

		Contact Constituent;
		HAM_Trivia__c Trivia;

		List<Contact> Constituents = [Select Id,HAM_Trivia_Attempted__c,HAM_Trivia_Attempted_Date__c,HAM_Trivia_Option_Chosen__c,HAM_Trivia_Score__c FROM Contact WHERE Id =: ContactId];

		if(!Constituents.isEmpty()){
			Constituent = Constituents[0];
		}

		List<HAM_Trivia__c> TriviaList = [Select Id,Active__c,Show_On_Portal__c,Order__c,Points__c,Question__c,
								(Select Id,Display_Order__c,Is_Correct__c,Option__c,Question__c FROM Trivia_Options__r ORDER BY  Display_Order__c ASC)
								FROM HAM_Trivia__c WHERE Active__c = True AND Show_On_Portal__c = True ORDER BY Order__c ASC LIMIT 1
			   				   ];

		 if(!TriviaList.isEmpty()){
			Trivia = TriviaList[0];
		}

		return new TriviaWrapper(Constituent,Trivia);
	}

	//Updates the constituent's trivia data after submission
	@AuraEnabled
	public static string updateTriviaInfoOnConstituent(Id ContactId,Integer Points,String SelectedOption){
		
		String returnValue;
		if(ContactId != Null){
			try{
				Contact Constituent = [SELECT Id,HAM_Trivia_Attempted_Date__c,HAM_Trivia_Option_Chosen__c,HAM_Trivia_Score__c
								   	   FROM Contact WHERE Id =: ContactId];
				Constituent.HAM_Trivia_Attempted_Date__c = Date.today();
				Constituent.HAM_Trivia_Option_Chosen__c = SelectedOption;
				Constituent.HAM_Trivia_Score__c =+ Points;

				Update Constituent;
				returnValue = 'Success';
			}catch(exception ex){
				returnValue = 'Unexpected Error Occured '+ex.getMessage();
				system.debug('Trivia Error '+ex.getMessage()+' at '+ex.getLineNumber());
			}
		}else{
			returnValue = 'Error - No ContactId';
		}

		return returnValue;

	}
}