force-app/main/default/objects/Contact/fields/ucinn_ascendv2__Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Contact_Type__c</fullName>
    <label>Constituent Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Trustee</fullName>
            </value>
            <value>
                <fullName>Hamilton Alumni</fullName>
            </value>
            <value>
                <fullName>Hamilton Withdrawn</fullName>
            </value>
            <value>
                <fullName>Kirkland Alumnae</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>Student on Leave</fullName>
            </value>
            <value>
                <fullName>Current Parent</fullName>
            </value>
            <value>
                <fullName>Parent on Leave</fullName>
            </value>
            <value>
                <fullName>Retiree</fullName>
            </value>
            <value>
                <fullName>Past Parent</fullName>
            </value>
            <value>
                <fullName>Grandparent</fullName>
            </value>
            <value>
                <fullName>Former Employee</fullName>
            </value>
            <value>
                <fullName>Spouse of Alumni or Trustee</fullName>
            </value>
            <value>
                <fullName>Surviving Spouse</fullName>
            </value>
            <value>
                <fullName>Parent of Withdrawn</fullName>
            </value>
            <value>
                <fullName>Estate</fullName>
            </value>
            <value>
                <fullName>Organization Contact</fullName>
            </value>
            <value>
                <fullName>Incoming Student</fullName>
            </value>
            <value>
                <fullName>Incoming Parent</fullName>
            </value>
            <value>
                <fullName>Friend</fullName>
                <default>true</default>
                <label>Friend</label>
            </value>
            <value>
                <fullName>Graduating Student</fullName>
            </value>
            <value>
                <fullName>Graduating Parent</fullName>
            </value>
            <value>
                <fullName>Tribute Donor</fullName>
            </value>
            <value>
                <fullName>Former Incoming Student</fullName>
            </value>
            <value>
                <fullName>Former Incoming Parent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/ucinn_ascendv2__Data_Source__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Data_Source__c</fullName>
    <label>Data Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ucinn_ascendv2__Data_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/SandboxContactEmailInvalidationBatchTest.cls
@isTest
public class SandboxContactEmailInvalidationBatchTest {
    @TestSetup
    static void makeData(){
        Contact con1 = new Contact(
            LastName = 'Test1',
            Email = 'con1@test.com',
            ucinn_ascendv2__Contact_Type__c = 'Friend',
            ucinn_ascendv2__Data_Source__c = 'SIS'
        );

        Contact con2 = new Contact(
            LastName = 'Test2',
            Email = 'con2@test.com',
            ucinn_ascendv2__Contact_Type__c = 'Friend',
            ucinn_ascendv2__Data_Source__c = 'SIS'
        );

        Contact con3 = new Contact(
            LastName = 'Test3',
            Email = 'con3@test.com',
            ucinn_ascendv2__Contact_Type__c = 'Friend',
            ucinn_ascendv2__Data_Source__c = 'SIS'
        );
        insert new List<Contact>{con1, con2, con3};
    }

    @isTest
    public static void runBatchClassSandboxEnv(){
        Test.startTest();

        SandboxContactEmailInvalidationBatch batch = new SandboxContactEmailInvalidationBatch();
        batch.isSandbox = true;

        Id batchJobId = Database.executeBatch(batch, 200);

        Test.stopTest();

        for(Contact con : [SELECT Id, Email FROM Contact]){
            Assert.areEqual('.invalid', con.Email.right(8));
        }
    }

    @isTest
    public static void runBatchClassProdEnv(){
        Test.startTest();

        SandboxContactEmailInvalidationBatch batch = new SandboxContactEmailInvalidationBatch();
        batch.isSandbox = false;

        Id batchJobId = Database.executeBatch(batch, 200);

        Test.stopTest();

        for(Contact con : [SELECT Id, Email FROM Contact]){
            Assert.areEqual('test.com', con.Email.right(8));
        }
    }
}